openapi: 3.0.0
info:
  title: A simple app
  version: 3.0.1
servers:
- url: /
paths:
  /files:
    get:
      description: Fetch list of items in from object storage
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_files_get_200_response_inner'
                type: array
          description: A list of items from the object bucket
        "500":
          description: Unable to fetch file list from S3 bucket
components:
  schemas:
    _files_get_200_response_inner:
      example:
        fileName: fileName
      properties:
        fileName:
          type: string

